spring:
  application:
    name: "clone-one-port"
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:13306/wanted_preonboarding?serverTimezone=UTC&characterEncoding=UTF-8
    username: wanted
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력

pg:
  tosspayments:
    baseUrl: "https://api.tosspayments.com/"
    privateKey: "test_sk_0RnYX2w532257LzwRYBK3NeyqApQ"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력